server:
  port: 1204
  servlet:
    context-path: /dispatch/admin
management:
  health:
    mail:
      enabled: false
  server:
    # 运行状况检查信息端点
    base-path: /actuator
spring:
  mvc:
    servlet:
      # Dispatcher Servlet 组件的启动时间默认为 -1，
      # 默认情况下，Dispatcher Servlet 组件将在第一个请求时动态加载，
      # 指定一个正整数或 0 以在程序启动后直接加载 Dispatcher Servlet
      load-on-startup: 0
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/t-dispatch?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 1204+
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 900000
      maximum-pool-size: 30
      minimum-idle: 10
      pool-name: HikariCP
      validation-timeout: 1000
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 2293297190@qq.com
    password: ncwylnztcushdjij
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true
mybatis-plus:
  configuration:
    # sql 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    
# T - 调度核心配置
tdispatch:
  # 核心调度线程池配置
  pool:
    # 高速触发线程池
    fast:
      # 核心线程数 - 要保留在池中的线程数
      corePoolSize: 10
      # 最大线程数 - 池中允许的最大线程数
      maximumPoolSize: 200
      # 存活时间 - 当线程数大于核心数时，这是多余的空闲线程在终止之前等待新任务的最长时间
      keepAliveTime: 60
    # 低速触发线程池
    slow:
      # 核心线程数 - 要保留在池中的线程数
      corePoolSize: 10
      # 最大线程数 - 池中允许的最大线程数
      maximumPoolSize: 100
      # 存活时间 - 当线程数大于核心数时，这是多余的空闲线程在终止之前等待新任务的最长时间
      keepAliveTime: 60