server:
  port: 1204
  servlet:
    context-path: /dispatch/admin
management:
  health:
    mail:
      enabled: false
  server:
    # Health check information endpoint
    base-path: /actuator
spring:
  mvc:
    servlet:
      # The startup timing of the Dispatcher Servlet component defaults to -1, 
      # by default the Dispatcher Servlet component will load dynamically on the first request, 
      # specifying a positive integer or 0 to load the Dispatcher Servlet directly after the program starts
      load-on-startup: 0
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/t-dispatch?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 1204+
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 900000
      maximum-pool-size: 30
      minimum-idle: 10
      pool-name: HikariCP
      validation-timeout: 1000
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 2293297190@qq.com
    password: ncwylnztcushdjij
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml